/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypack;

import database.DatabaseConnection;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import static mypack.car.buildTableModel;
import static mypack.car.sec;
import org.postgresql.jdbc.PgResultSetMetaData;
import utility.Bd_utility;

/**
 *
 * @author User
 */
public class iamge extends javax.swing.JFrame {

    /**
     * Creates new form iamge
     */
    public iamge() {
        initComponents();
Bd_utility.setImage(this,"image/wood3.jpg", 1406, 756);
                 this.getRootPane().setBorder(BorderFactory.createMatteBorder(5,5,5,5, Color.black));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        imagetable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtipath = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtiname = new javax.swing.JTextField();
        txtiprice = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        lblimage = new javax.swing.JLabel();
        txtidetail = new javax.swing.JTextField();
        btnstart = new javax.swing.JButton();
        btniadditem = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        timerlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Image Auction ");

        imagetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ImageName", "Image_details", "base price", "SOLD TO", "SOLD AT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        imagetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagetableMouseClicked(evt);
            }
        });
        imagetable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                imagetableComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(imagetable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Image Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Image Details*");

        txtipath.setBackground(new java.awt.Color(153, 94, 94));
        txtipath.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtipath.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("START PRICE");

        jButton1.setBackground(new java.awt.Color(45, 218, 193));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Select Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TIMER");

        txtiname.setBackground(new java.awt.Color(153, 94, 94));
        txtiname.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtiname.setForeground(new java.awt.Color(255, 255, 255));

        txtiprice.setBackground(new java.awt.Color(153, 94, 94));
        txtiprice.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtiprice.setForeground(new java.awt.Color(255, 255, 255));

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtidetail.setBackground(new java.awt.Color(153, 94, 94));
        txtidetail.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtidetail.setForeground(new java.awt.Color(255, 255, 255));

        btnstart.setBackground(new java.awt.Color(252, 97, 9));
        btnstart.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnstart.setText("Start Auction");
        btnstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstartActionPerformed(evt);
            }
        });

        btniadditem.setBackground(new java.awt.Color(45, 218, 193));
        btniadditem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btniadditem.setText("Add Item");
        btniadditem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniadditemActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("X");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        timerlabel.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        timerlabel.setForeground(new java.awt.Color(255, 0, 0));
        timerlabel.setText("1:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btniadditem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtidetail, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtiname, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtiprice, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtipath, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(890, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(251, 251, 251)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(timerlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(84, 84, 84))
                                    .addComponent(jLabel3))
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4)
                                .addGap(38, 38, 38)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btniadditem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtiname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(txtidetail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(txtiprice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(txtipath, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6)
                    .addContainerGap(693, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
JFileChooser fileChooser = new JFileChooser();
            int rs = fileChooser.showOpenDialog(null);
            if (rs == JFileChooser.APPROVE_OPTION) {
                File selectedImage = fileChooser.getSelectedFile();
                txtipath.setText(selectedImage.getAbsolutePath());
                lblimage.setIcon(resize(txtipath.getText()));
            }
               
    }//GEN-LAST:event_jButton1ActionPerformed
 public ImageIcon resize(String path) {
        ImageIcon myImg = new ImageIcon(path);
        Image image = myImg.getImage();
        Image newImage = image.getScaledInstance(322, 286, Image.SCALE_SMOOTH);
        ImageIcon finalpic =new  ImageIcon(newImage);
        adminImageData= finalpic;
        lblimage.setIcon(adminImageData); 
        return new  ImageIcon(newImage);
    }
   public void tableData() {
        try {
         String sql = "SELECT  imagename ,description, image_path, start_price,sold_to,sold_at FROM image_auction;";
                   //  String sql = "SELECT  * FROM image_auction;";

            Class.forName("org.postgresql.Driver");
                        Connection con = DatabaseConnection.getConnection();
                        Statement statement = con.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            imagetable.setModel(buildTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
   
    public void startTimer() {
        timer = new Timer(1000, (ActionEvent e) -> {
            sec--;
            if (sec == -1) {
                timer.stop();
                try {
                  //  fetchuser();
                } catch (Exception ex) {
                    Logger.getLogger(car.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (sec >= 0 && sec < 10) {
                timerlabel.setText("00:0" + sec);
            } else {
                timerlabel.setText("00:" + sec);
            }
        });
    }
      public static DefaultTableModel buildTableModel(ResultSet rs)
throws SQLException {
PgResultSetMetaData metaData = (PgResultSetMetaData) rs.getMetaData();
// names of columns
Vector<String> columnNames = new Vector<String>();
int columnCount = metaData.getColumnCount();
for (int column = 1; column <= columnCount; column++) {
columnNames.add(metaData.getColumnName(column));
}
// data of the table
Vector<Vector<Object>> data = new Vector<Vector<Object>>();
while (rs.next()) {
Vector<Object> vector = new Vector<Object>();
for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
vector.add(rs.getObject(columnIndex));
}
data.add(vector);
}
return new DefaultTableModel(data, columnNames);
}

   
    private void btnstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstartActionPerformed
                startTimer();
                timer.start();        
    }//GEN-LAST:event_btnstartActionPerformed

    private void btniadditemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniadditemActionPerformed
       String cname = txtiname.getText().trim();
    String detail = txtidetail.getText();
    String price = txtiprice.getText(); 
    String cpath=txtipath.getText();
                    if (txtiname.getText().isEmpty() || txtidetail.getText().isEmpty() || txtiprice.getText().isEmpty()|| txtipath.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"FEILDS EMPTY (put information properly)","Field Empty",JOptionPane.WARNING_MESSAGE);
 
              return;
            }

            
            try{
            
            Class.forName("org.postgresql.Driver");
            Connection con = DatabaseConnection.getConnection();
            
            String sql = "INSERT INTO image_auction (imagename, description, start_price, image_path) VALUES (?, ?, ?, ?)";
              java.sql.PreparedStatement statement = con.prepareStatement(sql);
                File f = new File(txtipath.getText());
                    InputStream inputStream = new FileInputStream(f);

                    statement.setString(1, cname);
                    statement.setString(2, detail); 
                    statement.setBigDecimal(3, new java.math.BigDecimal(price));
                    statement.setBinaryStream(4, inputStream);
                    statement.executeUpdate();
                    tableData();

                    JOptionPane.showMessageDialog(null, "INFORMATION ADDED SUCCESSFULLY" ,"SUCCESS",JOptionPane.INFORMATION_MESSAGE);

                    txtiname.setText("");
                    txtidetail.setText("");
                    txtiprice.setText("");
                    txtipath.setText("");
                    lblimage.setIcon(null);
                   
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                    
             
         

    }//GEN-LAST:event_btniadditemActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void imagetableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imagetableComponentShown
       /* try{
            fetchuser();
        }catch(Exception ex){
            ex.printStackTrace();
        }  */
    }//GEN-LAST:event_imagetableComponentShown

    private void imagetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagetableMouseClicked
DefaultTableModel dm = (DefaultTableModel) imagetable.getModel();
                int selectedRow = imagetable.getSelectedRow();
                adminNameData = dm.getValueAt(selectedRow, 0).toString();
                txtiname.setText(adminNameData);
               byte[] img = (byte[]) dm.getValueAt(selectedRow, 2); 
               //String img = dm.getValueAt(selectedRow, 3).toString();
                ImageIcon imageIcon = new ImageIcon(img);
                Image im = imageIcon.getImage();
                Image newimg = im.getScaledInstance(322, 286, Image.SCALE_SMOOTH);
                ImageIcon finalPic = new ImageIcon(newimg);
                adminImageData = finalPic;
                lblimage.setIcon(adminImageData);
                adminPriceData = dm.getValueAt(selectedRow, 3).toString();
                txtiprice.setText(adminPriceData);
                adminDetails = dm.getValueAt(selectedRow, 1).toString();
                txtidetail.setText(adminDetails);       
    }//GEN-LAST:event_imagetableMouseClicked
/**private void fetchuser()throws Exception{
    DefaultTableModel model=(DefaultTableModel) imagetable.getModel();
    model.setRowCount(0);
       try {
              Class.forName("org.postgresql.Driver");
            Connection con = (Connection) DatabaseConnection.getConnection();
            Statement st =con.createStatement();
            String query = "SELECT  imagename,description, start_price FROM image_auction;";
          
            ResultSet rs;
        rs = st.executeQuery(query);
            while(rs.next()){
                model.addRow(new Object[]{
                    rs.getString("imagename"),
                    rs.getString("description"),
                    rs.getString("start_price"),
                 
                });
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Somthing went wrong.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iamge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iamge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iamge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iamge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iamge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btniadditem;
    private javax.swing.JButton btnstart;
    private javax.swing.JTable imagetable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel timerlabel;
    private javax.swing.JTextField txtidetail;
    private javax.swing.JTextField txtiname;
    private javax.swing.JTextField txtipath;
    private javax.swing.JTextField txtiprice;
    // End of variables declaration//GEN-END:variables
  public static String adminDetails="";
public static String adminNameData="";
    public static String adminPriceData="";
    public static ImageIcon adminImageData;
    Timer timer;
    byte[] photo=null;
    String filename=null;
     public static int sec = 60;
}
